services:
  database:
    image: postgres:15
    container_name: single_template_local_rdb
    environment:
      POSTGRES_DB: single_template_local
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "55432:5432"
    volumes:
      - single_template-data:/var/lib/postgresql/data
    networks:
      - single_template-network

volumes:
  single_template-data:
    name: single_template-data

networks:
  single_template-network:
    name: single_template-network